### ISSUE TITLE
Game UX

### ISSUE THREAD

**Issue by bencbernstein** [Classical-SB/Apiary#11]
### Minor
- [x] Remove extraneous spaces from in between words in question prompt

### Game Animation
- [x] All color changes animate in and out on 0.2 Second Duration. This includes Hinting, Right Answer, Wrong Answer
- [x] Showing roots from hint animates change in text height (this might be hard)
- [x] When correct option chosen, button fades to `.honey` before new question is presented
- [x] When incorrect option chosen, button fades to `.red` then back to white
- [x] When correct answer achieved, need some simple global animation to signify this. Maybe a brief MIR like popup that says Good Job! or even as simple as color changes in background

### Hinting Animation
This may need smoothing, but currently unclear until more Akiva testing

### Design
- [x] Prefer Brandon Grotesque to Avenir Globally
- [x] Bigger component parts to fill in, this should be primary

### Fixes
- [x] Exit Game Button Exits Game (Currently Doesn't)
- [x]  Progress Bar animates a little faster, and only animates up when question is right

**Comment by OLI9292** [comment]
Showing roots from hint animates change in text height - how exactly does this work ? the root text animates up ?

**Comment by bencbernstein** [comment]
i think it'd have to be a two part animation ... the button increases in height and the definition fades in

it could also fade out just the root, and then fade in both of them together ... almost like 'flipping the card over'

**Comment by OLI9292** [comment]
hm ya ill think about this

**Comment by OLI9292** [comment]
ive been wondering about the question right animation too
