### ISSUE TITLE
Game View Controller

### ISSUE THREAD

**Issue by OLI9292** [Classical-SB/Apiary#4]
**Gameplay** - O
- [x] buttons should scramble *
- [x] autohinting
- [ ] tony-spatio bug *
- [ ] more roots
- [x] pause or other way to prevent button mashing *

**Design** - B
- [x] visual feedback for wrong answer * 
- [x] Distinguish roots typographically from definitions *
- [x] visual feedback for right answer
- [x] hint animations
- [x] text cutoff definition solution *
- [x] text cutoff root definition solution *
- [x] better button spacing

**Comment by bencbernstein** [comment]
can we specify better button spacing?
