### ISSUE TITLE
0.2 Tests

### ISSUE THREAD

**Issue by bencbernstein** [Classical-SB/Apiary#57]

**Comment by bencbernstein** [comment]
tutorial question two skips forward for some reason
speed round intermission isn't formatted right
after i played a speed round, it kept giving me more questions in normal expedition format

**Comment by OLI9292** [comment]
https://github.com/Classical-SB/Apiary/pull/54/files#diff-f4609971ad88e60b3fbfc0efca0b09a3L48 broke speedRoundActivated formatting cause all the cases weren't handled
